import { z } from 'zod';
import { defineNode } from '../schemas/node-definition';

export const llmPrompt = defineNode({
    id: 'llm.prompt',
    version: 1,
    displayName: 'LLM Prompt',
    description: 'Generates text using a language model. Use when the workflow needs to summarize, classify, transform, analyze, or generate content from information provided by previous nodes.',
    category: 'action',
    outputs: [{ id: 'main', label: 'Output' }],
    parameters: z.object({
        prompt: z.string().describe('The instruction to send to the language model. May contain {{...}} references to data from previous nodes.'),
        model: z.string().describe('The language model to use for generating the response.'),
        maxTokens: z.number().int().positive().optional().describe('Maximum number of tokens the language model can generate.')
    }),
    output: z.object({
        text: z.string().describe('The text generated by the language model.'),
    })
})